Add the unit tests for data preparation pipeline code
googleinterns/cl_analysis pull request #13
Opened 2020-09-23 07:31 UTC by peiranli

This pull request adds the unit tests for data collection, file level transformation, and file level aggregation code as well as the utils.

2020-09-23 20:01 UTC, shail229 commented on data/data_collection_test.py
> +        self.assertEqual(pull_request_review_time, 1589779284-1537057258)
What you are verifying here?
You should use mock_pull_request_info to mock the response of pull request and when you call the pull request, verify that not mock_pull_request_info.

2020-09-23 20:05 UTC, shail229 requested changes
You are not testing any of the DataCollector methods here. 
You should mock the DataCollector to return your mocked pull request result and then call DataCollector methods and verify their results.

2020-09-24 17:14 UTC, jinhongcgoogle approved these changes

2020-09-24 19:53 UTC, shail229 approved these changes

2020-09-24 20:54 UTC, merged